// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knrsjxphbczcfzamiawj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtucnNqeHBoYmN6Y2Z6YW1pYXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjA0OTUsImV4cCI6MjA2NTM5NjQ5NX0.R9ZtGqB1uHhKWKqffqMLH-SQFnrEpUB_gd22SUCrf6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);